name: Python CI/CD

on: 
  push:
    branches:
      - main  # Uruchamia workflow tylko dla zmian w głównej gałęzi
  pull_request:
    branches:
      - main  # Uruchamia workflow dla pull requestów do głównej gałęzi

jobs:
  test:
    runs-on: ubuntu-latest  # Określenie, na jakim systemie uruchomi się workflow (np. Ubuntu)
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Pierwszy krok to pobranie kodu repozytorium
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'  # Określenie wersji Pythona

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Instalowanie zależności

      - name: Lint with flake8
        run: |
          flake8 .  # Uruchomienie lintera flake8 w celu sprawdzenia jakości kodu

      - name: Test with pytest
        run: |
          pytest  # Uruchomienie testów przy pomocy pytest
